### ISSUE TITLE
Feature Request: Allow loading games from uma0: device?

### ISSUE THREAD

**Issue by rsn8887** [ammeir/vicevita#1]
Thanks for this great standalone emu. Some people (like me) store a lot of their roms on uma0: instead of ux0:. Maybe the functionality to choose uma0: as device for roms can be included in ViceVita? When going to parent many times, above root, it could show ux0: and uma0: devices to select, similar to how ScummVM and UAE4All2 does it?

It is not necessary, just a convenience really.

**Comment by ammeir** [comment]
Thank you, appreciate. I'm not very familiar with uma0: but I will definitely look into this. Thanks for the suggestion. Would I need a sd2vita adapter to test this?

**Comment by rsn8887** [comment]
I think so, yes. However, there's not much testing needed, file paths starting with 'uma0:' work just like 'ux0:' if the user has sd2vita mounted as uma0:. So you could just make an option to press a button to open uma0: instead of ux0: when browsing games or so.

**Comment by rsn8887** [comment]
I implemented this and made a PR, please take a look if you have some time.

You can now go to parent... parent.. parent... until you see a virtual "root" with entries:
```
ux0:
uma0:
```
useful for people like me who store game collections on uma0: . This is similar to how Retroarch, ScummVM, Vitashell and UAE4All2 do it, too.
