### ISSUE TITLE
Can't load side B.

### ISSUE THREAD

**Issue by Zmansk88** [ammeir/vicevita#5]
When playing a game it asks to insert side B but there seems to be no option to add another disk. Please add otherwise I can't play through some games.

**Comment by ammeir** [comment]
Please report the game you are having problems with. Normally you would go to Devices --> Drive --> Content, detach current disk and attach new (disk b) and you are good to go.

**Comment by Zmansk88** [comment]
Thank you for getting back to me. I didn't know you could do this

Sent via the Samsung Galaxy Note9, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by Zmansk88** [comment]
This works on all games I tried it.  Thanks for letting me know about this feature.

Sent via the Samsung Galaxy Note9, an AT&T 5G Evolution capable smartphone
Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
